version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/board
#    destination: /home/ubuntu/app/step2/zip
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runas: ubuntu